import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '@/Components/Common/badge';
import { Link } from 'react-router-dom';
import { ConfirmButton } from '@/Components/Common/ConfirmButton';
export default function EmployeeTable({ newAllUserTabledata }) {
    return (_jsxs("div", { className: "overflow-auto customScroll max-h-screen  w-full", children: [_jsxs("table", { className: "min-w-[1040px] w-full text-white text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: 'bg-[#212121] ', children: [_jsx("th", { className: 'p-6 rounded-l-lg', children: "-" }), _jsx("th", { className: 'w-1/7 ', children: "Employee ID" }), _jsx("th", { className: 'w-1/7 ', children: "Employee Name" }), _jsx("th", { className: 'w-1/7', children: "Job Title" }), _jsx("th", { className: 'w-1/7', children: "Line Manager" }), _jsx("th", { className: 'w-1/7', children: "Department" }), _jsx("th", { className: 'w-1/7', children: "Employee Status" }), _jsx("th", { className: 'w-1/7 rounded-r-lg', children: "Actions" })] }) }), newAllUserTabledata?.length > 0 &&
                        _jsx("tbody", { children: newAllUserTabledata?.map((item) => (_jsxs("tr", { className: 'text-center', children: [_jsx("td", { className: 'p-8', children: _jsx("input", { type: "checkbox" }) }), _jsxs("td", { className: 'p-8', children: [" ", _jsxs("div", { className: 'text-start', children: [_jsx(Link, { to: `/profile/${item.user_Ref._id}`, children: _jsx("p", { className: 'hover:underline', children: item.employeeCode || '-' }) }), _jsx("p", { className: 'text-xs text-gray-400', children: item.email })] })] }), _jsx("td", { className: 'p-8', children: _jsxs("div", { className: 'text-start', children: [_jsx("p", { children: item.name || '-' }), _jsx("p", { className: 'text-xs text-gray-400', children: item.email })] }) }), _jsx("td", { children: item.job_title || '-' }), _jsx("td", { children: "-" }), _jsx("td", { children: item.department }), _jsx("td", { children: _jsx(Badge, { className: "bg-green-800 px-4 py-2 text-white", children: "Active" }) }), _jsx("td", { children: _jsx("div", { className: 'flex gap-2 justify-center items-center', children: _jsx(ConfirmButton, { empID: item?._id }) }) })] }, item.id))) })] }), newAllUserTabledata?.length == 0 &&
                _jsx("h1", { className: 'font-script text-3xl flex justify-center font-bold text-nowrap mt-4 mb-4 ', children: "No Employee Record" })] }));
}
