import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import QuestionList from '@/Sections/Detailpayroll/QuestionList';
import { useState } from 'react';
import { FaChevronLeft } from "react-icons/fa";
import { QuestionListArray } from "../../../../public/Data2";
import { FaChevronDown } from 'react-icons/fa6';
export default function DetailPayroll() {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsx(_Fragment, { children: _jsxs("div", { className: 'bg-[#2B2B2B] p-4 rounded-lg', children: [_jsxs("div", { className: 'flex items-center gap-4', children: [_jsx(FaChevronLeft, {}), _jsx("h1", { className: 'text-2xl font-semibold', children: "Detail Payroll" })] }), _jsxs("div", { className: 'border p-4 rounded-lg mt-8 flex flex-col gap-6 max-h-[460px] customScroll overflow-auto', children: [_jsxs("div", { children: [_jsxs("div", { className: 'flex items-center gap-4', children: [_jsx("img", { src: "/images/blank-profile-picture-973460_1280.webp", alt: "", className: 'w-16 h-16 rounded-full ' }), _jsxs("div", { children: [_jsx("h1", { className: 'font-semibold text-2xl', children: "Zohaib Ali" }), _jsx("p", { className: 'opacity-50 text-[14px]', children: "Mern Stack" })] })] }), _jsx("div", { children: _jsxs("div", { className: 'grid grid-cols-2 mt-4 ', children: [_jsxs("div", { className: 'flex flex-col gap-4', children: [_jsx("p", { className: 'opacity-50 text-[14px]', children: "Emplopyee Code" }), _jsx("p", { className: 'opacity-50 text-[14px]', children: "Emplopyee Status" }), _jsx("p", { className: 'opacity-50 text-[14px]', children: "Joining Date" })] }), _jsxs("div", { className: 'flex flex-col gap-4', children: [_jsx("h1", { className: 'font-semibold ', children: "Emp101" }), _jsx("h1", { className: 'font-semibold ', children: "Active" }), _jsx("h1", { className: 'font-semibold ', children: "16 Feb 20" })] })] }) })] }), _jsx("div", { children: _jsx("ul", { children: QuestionListArray.map((item) => {
                                    return (_jsx(QuestionList, { id: item.id, title: item.title }, item.id));
                                }) }) }), _jsx("div", { children: _jsxs("div", { className: 'rounded-[8px]  p-5  border mb-2 ', children: [_jsxs("div", { className: 'flex justify-between items-center', children: [_jsx("h1", { className: ' font-bold mb-2', children: "Bank Information" }), _jsx(FaChevronDown, { className: `cursor-pointer ${isOpen && `rotate-180`}`, onClick: () => { setIsOpen(!isOpen); } })] }), isOpen &&
                                        _jsxs("div", { className: 'grid grid-cols-2 mt-4 ', children: [_jsxs("div", { className: 'flex flex-col gap-4', children: [_jsx("p", { className: 'opacity-50 text-[14px]', children: "Bank Name" }), _jsx("p", { className: 'opacity-50 text-[14px]', children: "Acc Name" }), _jsx("p", { className: 'opacity-50 text-[14px]', children: "Acc Number" })] }), _jsxs("div", { className: 'flex flex-col gap-4', children: [_jsx("h1", { className: 'font-semibold ', children: "HBL" }), _jsx("h1", { className: 'font-semibold ', children: "Zohaib" }), _jsx("h1", { className: 'font-semibold ', children: "08070778979087" })] })] })] }) })] })] }) }));
}
